/*
 * NOROSA Relay - over-the-wire protocol types.
 *
 * The server only understands *envelopes*. Every payload that travels
 * through the relay is treated as an opaque string — the server never
 * inspects, parses, or logs message contents.
 *
 * Data flow (metadata minimised):
 *   client ──▶ {t:'keys.upload', roomCode, keys}     public keys for a room
 *   client ──▶ {t:'keys.get',    roomCode, txn}      fetch other members' keys
 *   relay  ──▶ {t:'keys.result', txn, users}         one-time prekey already consumed
 *   client ──▶ {t:'msg', roomCode, to, payload}      ciphertext only
 *   relay  ──▶ {t:'msg', from, payload}              delivered, then purged
 *   client ──▶ {t:'room.destroy', roomCode}          wipe every trace of the room
 */

/** A single anonymous device inside a room. Generated by the server, no PII. */
export interface RoomMember {
  /** Identity key offered by the client. The server cannot read it, it just stores it. */
  identityKey: string
  /** Ed25519 identity key (for verifying the signed pre-key signature). */
  ed25519: string
  /** Signed pre-key value, as produced by the client's Olm account. */
  signedPrekey: string
  /** Ed25519 signature over the signed pre-key, made by the client's identity key. */
  signedPrekeySig: string
}

/** One one-time pre-key. Consumed once by the server when handed to a peer. */
export interface OneTimePrekey {
  keyId: string
  key: string
}

/** Client → Relay: register / refresh this member's public key bundle. */
export interface UploadKeysMessage {
  t: 'keys.upload'
  roomCode: string
  keys: RoomMember
  oneTimeKeys: OneTimePrekey[]
}

/** Client → Relay: request the public key bundles of every other room member. */
export interface GetKeysMessage {
  t: 'keys.get'
  roomCode: string
  /** Correlation token so the client can match the response. */
  txn: string
}

/** Relay → Client: answer to `keys.get`. */
export interface KeysResultMessage {
  t: 'keys.result'
  txn: string
  /** Keyed by anonymous alias of each peer. */
  users: Record<string, { keys: RoomMember; oneTimeKey?: OneTimePrekey }>
}

/** Client → Relay: enqueue / deliver an opaque ciphertext payload. */
export interface RelayMessage {
  t: 'msg'
  roomCode: string
  /** Target anonymous alias, or '*' to broadcast to every other member. */
  to: string
  /** Client-generated message id (random UUID) used for acknowledgements. */
  id: string
  /** Encrypted payload. The server never touches the contents. */
  payload: string
}

/** Relay → Client: a delivered message. */
export interface DeliveredMessage {
  t: 'msg'
  from: string
  id: string
  payload: string
}

/**
 * Client → Relay: a single opaque WebRTC signaling frame (SDP offer/answer
 * or a trickled ICE candidate). The relay routes it exactly like `msg` and
 * never parses it; in practice the body is ALREADY ciphertext because the
 * call planes ride the same double ratchet as chat (see `k:'call'` in the
 * client's envelope format). This keeps even ICE IPs away from the server.
 */
export interface CallMessage {
  t: 'call'
  roomCode: string
  to: string
  id: string
  payload: string
}

/** Relay → Client: a delivered call-signaling frame. */
export interface DeliveredCall {
  t: 'call'
  from: string
  id: string
  payload: string
}

/** Client → Relay: every room record, key, and mailbox entry is destroyed. */
export interface DestroyRoomMessage {
  t: 'room.destroy'
  roomCode: string
}

/**
 * Client → Relay: initial handshake binding this socket to a room.
 *
 * `roomCode` carries ONLY the SHA-256 of the human code (see roomcode.ts) —
 * the relay sees a digest it can compare, never a secret it could disclose.
 * `create` tells the relay whether this client invents the room (create) or
 * must join one that already exists (join). A join to a missing room fails;
 * a typo can never quietly mint a new room.
 */
export interface HelloMessage {
  t: 'hello'
  roomCode: string
  create: boolean
}

/** Relay → Client: structural acknowledgements and errors. */
export interface AckMessage {
  t: 'ack'
  id?: string
}
export interface ErrorMessage {
  t: 'error'
  code: string
  message: string
}
export interface MailboxMessage {
  t: 'mailbox'
  messages: DeliveredMessage[]
}

/** Discriminated union of everything the relay understands. */
export type WireMessage =
  | HelloMessage
  | UploadKeysMessage
  | GetKeysMessage
  | RelayMessage
  | CallMessage
  | DestroyRoomMessage

export const MAX_PAYLOAD_BYTES = 64 * 1024
export const MAILBOX_TTL_MS = 24 * 60 * 60 * 1000